version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."

      # Define variables
      - |
        GITHUB_API_URL="https://api.github.com"
        ORG_NAME="your-org-name"
        GITHUB_PAT="$GITHUB_PAT"
        PER_PAGE=100  # Number of results per page
        PAGE=1
        ALL_MEMBERS=""

      # Fetch all members across multiple pages
      - |
        while true; do
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_PAT" \
              "$GITHUB_API_URL/orgs/$ORG_NAME/members?page=$PAGE&per_page=$PER_PAGE")

          # Check if response is empty or error occurred
          if [ -z "$RESPONSE" ] || [ "$RESPONSE" == "[]" ]; then
            break
          fi

          MEMBERS=$(echo "$RESPONSE" | jq -r '.[].login')
          if [ -n "$MEMBERS" ]; then
            ALL_MEMBERS+="$MEMBERS"$'\n'
          fi

          echo "Fetched page $PAGE"
          ((PAGE++))
        done

      - echo "All members fetched:"
      - echo "$ALL_MEMBERS"
