version: 0.2

phases:
  build:
    commands:
      - echo "Downloading a file"
      - aws s3 cp s3://<bucket-name>/dag/test_file.py ./test_file.py
      - grep -n 'task_id="run_fdl_dbjob_' test_file.py | while IFS=: read -r line_number job_string; do
          job_name=$(echo $job_string | sed 's/task_id="run_//; s/"//');
          job_id=$(curl --silent --request GET "https://<dbr_base_url>/api/2.1/jobs/list?name=$job_name" \
            --header "Authorization:Bearer $DBR_TOKEN" | jq -r '.jobs[] | select(.settings.name=="'"$job_name"'") | .job_id');
          sed -i "${line_number}s/job_id,*/job_id=${job_id},/" test_file.py;
          echo "Replaced job_id for $job_name at line $line_number with $job_id";
        done

      - echo "Updated test_file.py:"
      - echo "Uploading back to  s3 with updated file"
      - aws s3 cp ./test_file.py s3://<bucket-name>/dag/test_file.py
  post_build:
    commands:
      - echo "Successful."
