version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."

      # Define variables
      - |
        GITHUB_API_URL="https://api.github.com"
        ORG_NAME="your-org-name"
        GITHUB_PAT="$GITHUB_PAT"
        PER_PAGE=100
        ALL_COLLABORATORS=""

      # Get all repositories in the organization
      - |
        PAGE=1
        ALL_REPOS=""

        while :; do
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_PAT" \
              "$GITHUB_API_URL/orgs/$ORG_NAME/repos?page=$PAGE&per_page=$PER_PAGE")

          if [ -z "$RESPONSE" ] || [ "$RESPONSE" = "[]" ]; then
            break
          fi

          REPOS=$(echo "$RESPONSE" | jq -r '.[].name')
          ALL_REPOS+="$REPOS"$'\n'
          echo "Fetched repos page $PAGE"
          ((PAGE++))
        done

      # Fetch collaborators for each repo
      - |
        for REPO in $ALL_REPOS; do
          PAGE=1
          while :; do
            COLLAB_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_PAT" \
                "$GITHUB_API_URL/repos/$ORG_NAME/$REPO/collaborators?page=$PAGE&per_page=$PER_PAGE")

            if [ -z "$COLLAB_RESPONSE" ] || [ "$COLLAB_RESPONSE" = "[]" ]; then
              break
            fi

            COLLABS=$(echo "$COLLAB_RESPONSE" | jq -r '.[] | select(.permissions.admin == false) | .login')
            ALL_COLLABORATORS+="$COLLABS"$'\n'
            echo "Fetched collaborators from repo: $REPO (Page $PAGE)"
            ((PAGE++))
          done
        done

      - echo "All outside collaborators:"
      - echo "$ALL_COLLABORATORS"
