name: "Terraform Provision Request"
description: "Trigger Terraform/Terragrunt workflow"
title: "[Terraform]: "
labels:
  - terraform-provision

body:
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Environment to deploy to (dev / qa / prod)"
      placeholder: dev
    validations:
      required: true

  - type: input
    id: git_branch
    attributes:
      label: Git Branch
      description: "Branch to deploy from"
      placeholder: feature/login-api
    validations:
      required: true

  - type: dropdown
    id: wait_for_approval
    attributes:
      label: Wait for approval?
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: dropdown
    id: terraform_command
    attributes:
      label: Terraform command
      options:
        - terragrunt
        - terraform
    validations:
      required: true
