name: Deploy Workflow

on:
  workflow_dispatch:  # Allows manual/API trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "This workflow was triggered via API!"

